config/routes.rb
Catalog::Application.routes.draw do
  devise_for :admins

  devise_for :users
  root :to => "categories#index"
  resource :admins
  resources :categories do
    resources :offers
  end
  namespace :admin do
    resources :offers
  end

  namespace :admin do
    resources :categories do
      resources :offers do
      end
      end
  end
  end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :offers , :dependent=>:destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :offers , :dependent=>:destroy
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
 # before_filter :authenticate_admin!
  layout 'admin'
  def index
    @categories=Category.all
  end
  def new
    @category=Category.new
  end
  def create
    @category=Category.new(params[:category])
    @category.save
    redirect_to admin_categories_path(@categories)
  end
  def edit
    @category=Category.find(params[:id])
  end
  def show
    @category=Category.find(params[:id])

  end
  def update
    @category=Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to admin_categories_path(@categories)
  end

  def destroy
    @category=Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path(@categories)
  end
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
 # before_filter :authenticate_admin!

  def index
    @cats=Cat.all
  end
  def new
    @cats=Cat.new
  end
  def create
    @cats=Cat.new(params[:cat])
    @cats.save
    redirect_to admin_cat_path(@cats)
  end
  def edit
    @cats=Cat.find(params[:id])
  end
  def show
    @cats=Cat.find(params[:id])

  end
  def update
    @cats=Cat.find(params[:id])
    @cats.update_attributes(params[:cat])
    redirect_to admin_cat_path(@cats)
  end
  def destroy
    @cats=Cat.find(params[:id])
    @cats.destroy
    redirect_to admin_cats_path(@cats)
  end
end

app/controllers/admin/offers_controller.rb
class Admin::OffersController < ApplicationController
  layout 'admin'
  def index
    @category=Category.find(params[:category_id])
    @offers=@category.offers.all
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer=Offer.new(params[:offer])
    @offer.save
    redirect_to admin_categories_path
  end


  def edit
    @offer=Offer.find(params[:id])
  end

  def show
    @offer=Offer.find(params[:id])
  end

  def update
    @offer=Offer.find(params[:id])
    @offer.update_attributes(params[:offer])
    redirect_to admin_categories_path(@category)
  end

  def destroy
    @offer=Offer.find(params[:id])
    @offer.destroy
    redirect_to admin_categories_path(@category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 #before_filter :authenticate_user!
  def index
   @categories=Category.all
  end

  #def edit
  #  @catalog=Category.find(params[:id])
  #end
  #
  def show
    @categories=Category.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
 #before_filter :authenticate_user!
  def  index
   @cats=Cat.all
  end


  def edit
    @cats=Cat.find(params[:id])
  end

  def show
    @cats=Cat.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @category=Category.find(params[:category_id])
    @offers=@category.offers.all
  end

  def show
    @offer=Offer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/cat_helper.rb
module Admin::CatHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers2_helper.rb
module Offers2Helper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/cats/_form.html.erb
<%=simple_form_for @cats, :url => {:action =>"update"} do |f| %>
    <%= f.input :title %>
    <div class="form-actions">
      <%= f.button :submit, :class => 'btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admin_cats_path, :class => 'btn' %>
    </div>
<% end %>

app/views/admin/cats/_form.html.haml
=simple_form_for @cats, :url => {:action =>"update"} do |f| 
    = f.input :title
    .form-actions
    =f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admin_cats_path, :class => 'btn' 

app/views/admin/cats/edit.html.erb
<%=render 'form' %>

app/views/admin/cats/edit.html.haml
=render 'form'

app/views/admin/cats/index.html.erb
<%- model_class = Cat.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:title) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @cats.each do |cat| %>
      <tr>
        <td><%= link_to cat.title, admin_cat_path(cat), :class=>'btn btn-large btn-primary disabled' %></td>
        <td><%=l cat.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_cat_path(cat), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cat_path(cat),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("Новый каталог")),
            new_admin_cat_path(:id),
            :class => 'btn btn-primary' %>
<%= link_to t('Создать', :default => t("Создать обьявление")),
            new_admin_offer_path,
            :class => 'btn btn-group' %>

app/views/admin/cats/index.html.haml
%table
- @cats.each do |cat|
  %tr
    %td= link_to cat.title, admin_cat_path(cat), :class=>'btn btn-large btn-primary disabled'
    %td=l cat.created_at
    %td= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_cat_path(cat), :class => 'btn btn-mini'
    = link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cat_path(cat),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger'

  %br
= link_to t('.new', :default => t("Новый каталог")),
            new_admin_cat_path(:id),
            :class => 'btn btn-primary'
= link_to t('Создать', :default => t("Создать обьявление")),
            new_admin_offer_path,
            :class => 'btn btn-group'

app/views/admin/cats/new.html.erb
<%=render 'form' %>

app/views/admin/cats/new.html.haml
=render 'form'

app/views/admin/cats/show.html.erb
<%= @cats.title %>
<%=link_to 'Назад', admin_cats_path %>
<BR>
    <%=@cats.offers.each do |p| %>
        <ul class="nav nav-tabs nav-stacked">
          <li class="active"><a href="#"><%=p.title%></a></li>
          <li><a href="#"><%= p.description %></a></li>
          <li><a href="#"><%= p.short_description %></a></li>
          <li><a href="#"><%= p.phone1 %></a></li>
          <li><a href="#"> <%= p.phone2 %></a></li>
          <li><a href="#"><%= p.email %></a></li>
          <li><a href="#"><%= p.city %></a></li>
          <li><a href="#"> <%= p.address %></a></li>
        </ul>

    <%= link_to "Удалить",admin_offer_path(p), :method => :delete  %>
    <%= link_to "Изменить",edit_admin_offer_path(p.id)  %>
    <HR>
<%end%>

app/views/admin/cats/show.html.haml
= @cats.title 
=link_to 'Назад', admin_cats_path 
%br
  %table
  -@cats.offers.each do |p|
    %tr= p.title
    %tr= p.description
    %tr= p.short_description
    %tr= p.phone1
    %tr= p.phone2
    %tr= p.email
    %tr= p.city
    %tr= p.address
    =link_to "Удалить",admin_offer_path(p), :method => :delete
    =link_to "Изменить",edit_admin_offer_path(p.id)

app/views/admin/offers/_form.html.erb
<div class="page-header">
  <h1>Создаем Обьявления</h1>
</div>

<%=  simple_form_for [ :admin, @offer] do |f| %>
    <%= f.input :title, label: "Название", :class=>'input-xlarge focused'%>
    <%= f.text_area :description%> <br>

    <%= f.text_field :short_description %>
    <%= f.input :phone1, :class=>'input-xlarge focused' %>
    <%= f.input :phone2 %>
    <div class="input-prepend">
      <span class="add-on">@</span>
    <%= f.email_field :email, :class=>'span2' %>
    </div>
    <%= f.input :city %>
    <%= f.input :address %>
    <%=f.association :cat, :class=>'span2' %>

    <%= f.button :submit, :class=>'btn btn-success'  %>
<%end%>

app/views/admin/offers/_form.html.haml
%h1 Создаем Обьявление
=simple_form_for [:admin, @offer] do |f|
  =f.input :title
  =f.text_area :description
  %br
  =f.text_field :short_description
  =f.input :phone1
  =f.input :phone2
  =f.email_field :email
  =f.input :city
  =f.input :address
  =f.association :category
  =f.button :submit, :class=>'btn btn-success'

app/views/admin/offers/edit.html.erb
<%=render 'form'  %>

app/views/admin/offers/edit.html.haml
=render 'form'

app/views/admin/offers/index.html.erb
<%=link_to "Новая обьява", new_admin_offer_path %>

app/views/admin/offers/index.html.haml
%br
%table
  %tr
    %th Title
    %th Description
    %th Short_description
    %th phone1
    %th phone2
    %th email
    %th city
    %th address
    %th
  -@offers.each do |offer|
    %tr
      %td= offer.title
      %td= offer.description
      %td= offer.short_description
      %td= offer.phone1
      %td= offer.phone2
      %td= offer.email
      %td= offer.city
      %td= offer.address
      %td
      %td= link_to "Удалить",admin_offer_path(offer.id), :method => :delete
      %td= link_to "Изменить",edit_admin_offer_path(offer.id)

=link_to 'Назад', admin_categories_path

app/views/admin/offers/new.html.erb
<%=render 'form'%>

app/views/admin/offers/new.html.haml
=render 'form'

app/views/admin/offers/show.html.erb
    <%= @offer.title %> <BR>
    <%= @offer.description %>  <BR>
    <%= @offer.short_description %>  <BR>
    <%=@offer.phone1 %>  <BR>
    <%=@offer.phone2 %>  <BR>
    <%= @offer.email %> <BR>
    <%= @offer.city %>  <BR>
    <%= @offer.address %>
    <%= @offer.id %>
    <HR>

app/views/cats/_form.html.erb
<%= simple_form_for @cat, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cats_path, :class => 'btn' %>
  </div>
<% end %>

app/views/cats/index.html.erb
<%- model_class = Cat.new.class -%>
<h1><%=t '.title', :default => 'Cписок каталогов' %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= 'Название' %></th>
      <th><%= 'Дата создания' %></th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= link_to cat.title, cat_path(cat), :class=>'btn btn-large btn-primary disabled' %></td>
        <td><%=l cat.created_at %></td>
        <td>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/cats/index.html.haml
- model_class = Cat.new.class
%h1=t '.title', :default => 'Cписок каталогов'
%table{:class=>"table table-striped"}
  %tr
    %th= 'Название'
    %th= 'Дата создания'
  - @cats.each do |cat|
    %tr
      %td= link_to cat.title, cat_path(cat), :class=>'btn btn-large btn-primary disabled'
      %td=l cat.created_at
      %td

app/views/cats/new.html.erb
<%=simple_form_for @cats do |f| %>
<b>Enter name of catalog</b>
<%= f.text_field :title %>
<%= f.submit("Create") %>
<%-end%>

app/views/cats/show.html.erb
<span class="label"><%= @cats.title %></span>
<br>
<%=link_to 'Назад',cats_path %>


<%=@cats.offers.each do |p| %>
<ul class="nav nav-tabs nav-stacked">
  <li class="active"><a href="#"><%=p.title%></a></li>
  <li><a href="#"><%= p.description %></a></li>
  <li><a href="#"><%= p.short_description %></a></li>
  <li><a href="#"><%= p.phone1 %></a></li>
  <li><a href="#"> <%= p.phone2 %></a></li>
  <li><a href="#"><%= p.email %></a></li>
  <li><a href="#"><%= p.city %></a></li>
  <li><a href="#"> <%= p.address %></a></li>
</ul>
<%end%>

app/views/cats/show.html.haml
=@cats.title
=link_to 'Назад',cats_path
%br
=@cats.offers.each do |p|
  =p.title
  =p.description
  =p.short_description
  =p.phone1
  =p.phone2
  =p.email
  =p.city
  =p.address
  %br
  %br
 

app/views/offers/_form.html.erb
<%= simple_form_for @offer, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :short_description %>
  <%= f.input :phone1 %>
  <%= f.input :phone2 %>
  <%= f.input :email %>
  <%= f.input :city %>
  <%= f.input :address %>
  <%= f.input :cat_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<%- model_class = @offer.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/offers/index.html.erb
<%- model_class = Offer.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:short_description) %></th>
      <th><%= model_class.human_attribute_name(:phone1) %></th>
      <th><%= model_class.human_attribute_name(:phone2) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:cat_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= link_to offer.id, offer_path(offer) %></td>
        <td><%= offer.title %></td>
        <td><%= offer.description %></td>
        <td><%= offer.short_description %></td>
        <td><%= offer.phone1 %></td>
        <td><%= offer.phone2 %></td>
        <td><%= offer.email %></td>
        <td><%= offer.city %></td>
        <td><%= offer.address %></td>
        <td><%= offer.cat_id %></td>
        <td><%=l offer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_offer_path(offer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      offer_path(offer),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_offer_path,
            :class => 'btn btn-primary' %>

app/views/offers/index.html.haml
%br
%table
  %tr
    %th Title
    %th Description
    %th Short_description
    %th phone1
    %th phone2
    %th email
    %th city
    %th address
    %th
  -@offers.each do |offer|
    %tr
      %td= offer.title
      %td= offer.description
      %td= offer.short_description
      %td= offer.phone1
      %td= offer.phone2
      %td= offer.email
      %td= offer.city
      %td= offer.address
      %td
=link_to 'Назад',categories_path
 

app/views/offers/new.html.erb
<%- model_class = @offer.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/offers/show.html.erb
<%- model_class = @offer.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @offer.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @offer.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:short_description) %>:</strong></dt>
  <dd><%= @offer.short_description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone1) %>:</strong></dt>
  <dd><%= @offer.phone1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone2) %>:</strong></dt>
  <dd><%= @offer.phone2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @offer.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @offer.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @offer.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cat_id) %>:</strong></dt>
  <dd><%= @offer.cat_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              offers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_offer_path(@offer), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              offer_path(@offer),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>