config/routes.rb
Catalog::Application.routes.draw do
  devise_for :admins

  devise_for :users
  root :to => "categories#index"
  resource :admins
  resources :categories do
    resources :offers
  end
  namespace :admin do
    resources :offers
  end

  namespace :admin do
    resources :categories do
      resources :offers do
      end
      end
  end
  end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :offers , :dependent=>:destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :offers , :dependent=>:destroy
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
 # before_filter :authenticate_admin!
  layout 'admin'
  def index
    @categories=Category.all
  end
  def new
    @category=Category.new
  end
  def create
    @category=Category.new(params[:category])
    @category.save
    redirect_to admin_categories_path(@categories)
  end
  def edit
    @category=Category.find(params[:id])
  end
  def show
    @category=Category.find(params[:id])

  end
  def update
    @category=Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to admin_categories_path(@categories)
  end

  def destroy
    @category=Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path(@categories)
  end
end

app/controllers/admin/cats_controller.rb
class Admin::CatsController < ApplicationController
 # before_filter :authenticate_admin!

  def index
    @cats=Cat.all
  end
  def new
    @cats=Cat.new
  end
  def create
    @cats=Cat.new(params[:cat])
    @cats.save
    redirect_to admin_cat_path(@cats)
  end
  def edit
    @cats=Cat.find(params[:id])
  end
  def show
    @cats=Cat.find(params[:id])

  end
  def update
    @cats=Cat.find(params[:id])
    @cats.update_attributes(params[:cat])
    redirect_to admin_cat_path(@cats)
  end
  def destroy
    @cats=Cat.find(params[:id])
    @cats.destroy
    redirect_to admin_cats_path(@cats)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 #before_filter :authenticate_user!
  def index
   @categories=Category.all
  end

  #def edit
  #  @catalog=Category.find(params[:id])
  #end
  #
  def show
    @categories=Category.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
 #before_filter :authenticate_user!
  def  index
   @cats=Cat.all
  end


  def edit
    @cats=Cat.find(params[:id])
  end

  def show
    @cats=Cat.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @category=Category.find(params[:category_id])
    @offers=@category.offers.all
  end

  def show
    @offer=Offer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/admin/cat_helper.rb
module Admin::CatHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/cats_helper.rb
module Admin::CatsHelper
end

app/helpers/admin/offers_helper.rb
module Admin::OffersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/offers2_helper.rb
module Offers2Helper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/_form.html.haml
=simple_form_for [:admin, @category] do |f|
    = f.input :title
    .form-actions
    =f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")),
                  admin_categories_path, :class => 'btn'

app/views/admin/categories/edit.html.haml
=render 'form'

app/views/admin/categories/index.html.haml
%table{:class=>"table table-striped"}
- @categories.each do |cat|
  %tr
    %td= link_to cat.title, admin_category_offers_path(cat), :class=>'btn btn-large btn-primary disabled'
    %td=l cat.created_at
    %td= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_category_path(cat), :class => 'btn btn-mini'
    = link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_category_path(cat),
                      :method =>:delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger'

  %br
= link_to t('.new', :default => t("Новый каталог")),
            new_admin_category_path(:id),
            :class => 'btn btn-primary'
= link_to t('Создать', :default => t("Создать обьявление")),
            new_admin_offer_path,
            :class => 'btn btn-group'

app/views/admin/categories/new.html.haml
=render 'form'

app/views/categories/index.html.haml
- model_class = Category.new.class
%h1=t '.title', :default => 'Cписок каталогов'
%table{:class=>"table table-striped"}
  %tr
    %th= 'Название'
    %th= 'Дата создания'
  - @categories.each do |cat|
    %tr
      %td= link_to cat.title, category_offers_path(cat.id), :class=>'btn btn-large btn-primary disabled'
      %td=l cat.created_at
      %td